// ──────────────────────────────────────────────
// BRAND DATA
// ──────────────────────────────────────────────

export const BRAND = {
  name: 'The Bakerman Cafe',
  nameKannada: 'Le Café Bakerman',
  tagline: 'Artisan Desserts & Specialty Coffee',
  subtitle: 'Pâtisserie Artisanale • Gâteaux • Café de Spécialité',
  address: 'Boys Town Rd, Anandwan Colony, Parijat Nagar, Nashik, Maharashtra 422002',
  addressLines: [
    'Boys Town Road',
    'Anandwan Colony, Parijat Nagar',
    'Nashik, Maharashtra 422002',
  ],
  city: 'Nashik',
  phone: '+91 9730668223',
  phoneClean: '9730668223',
  rating: 4.7,
  reviewCount: '19',
  mapsLink: 'https://maps.app.goo.gl/droaCFWFs9gp3YMW9',
  instagram: 'https://instagram.com/thebakerman.co',
  instagramHandle: 'thebakerman.co',
  whatsappBase: 'https://wa.me/919730668223',
  languageCode: 'fr',
  dietaryType: 'Pure veg',

  // Editorial Copy
  heroQuote: 'Baked with intention. Served with warmth.',
  heroStory: 'Every cheesecake baked fresh. Every cup pulled from a proper machine. The Bakerman is Nashik\'s quiet obsession for anyone who takes dessert seriously.',
  signaturesTitle: 'Three reasons to visit',
  signaturesSubtitle: 'A Nutella cheesecake that holds its shape, a cold brew that lingers, and a brownie tub built for one — these are what the regulars come back for.',
  menuBoardTitle: 'The board',
  menuBoardSubtitle: 'Everything we bake and brew, every day. Tap add to build a takeaway order — it goes out as a WhatsApp message you send yourself.',
  visitTitle: 'Find us in Parijat Nagar',
  visitDescription: 'A cozy café on Boys Town Road with warm décor and proper coffee machines. Open every day, 11 AM to 11 PM — no rush hour, just good desserts.',
  cateringNote: 'Celebration cakes and custom orders — reach us on WhatsApp. Whole cheesecakes and brownie cakes available to pre-order.',
  packagingNote: 'Takeaway packed to keep fresh',
  taxNote: 'Prices in rupees, taxes included',
}

// ──────────────────────────────────────────────
// OPERATING HOURS (IST)
// Continuous 11 AM – 11 PM, open 7 days
// ──────────────────────────────────────────────

export const HOURS = {
  morning: { openMin: 660, closeMin: 1380, label: 'All Day Service' }, // 11:00 AM – 11:00 PM
  evening: null, // No split shift
  holidayDay: null, // Open 7 days a week
  holidayName: null,
  holidayLabel: null,
  shifts: [
    { name: 'Open daily', time: '11:00 AM – 11:00 PM', dot: 'bg-open-dot' },
  ],
}

// ──────────────────────────────────────────────
// MENU ITEMS (The Bakerman Cafe Official Menu)
// With European culinary translations
// ──────────────────────────────────────────────

export const MENU_ITEMS = [
  // ── DESSERTS ──
  {
    id: 1,
    name: 'Nutella Brownie Tub',
    subtitle: 'Gâteau fondant au Nutella',
    description: 'Rich, fudgy eggless Nutella brownie tub. Deeply chocolatey, gooey, and packed with authentic nutty goodness.',
    price: 200,
    category: 'Desserts',
    spiceLevel: 0,
    tags: ['signature', 'bestseller'],
    zone: 'cream',
    image: '/images/signature-1.jpg',
    prep: 'Eggless • Fudgy • Nutella',
  },
  {
    id: 2,
    name: 'Lotus Biscoff Brownie Tub',
    subtitle: 'Brownie au spéculoos Lotus',
    description: 'Fudgy veg brownie loaded with crunchy Lotus Biscoff spread and rich caramel flavour.',
    price: 200,
    category: 'Desserts',
    spiceLevel: 0,
    tags: ['bestseller'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Lotus Biscoff • Caramel',
  },
  {
    id: 3,
    name: 'Nutella Cheesecake Tub',
    subtitle: 'Torta al formaggio e Nutella',
    description: 'Creamy eggless cheesecake layered with rich, velvety Nutella.',
    price: 250,
    category: 'Desserts',
    spiceLevel: 0,
    tags: ['signature', 'bestseller'],
    zone: 'cream',
    image: '/images/signature-2.jpg',
    prep: 'Eggless • Baked • Nutella',
  },
  {
    id: 4,
    name: 'Lotus Biscoff Cheesecake Tub',
    subtitle: 'Cheesecake al caramello Biscoff',
    description: '100% veg cheesecake with silky cream cheese and crunchy caramelized Biscoff biscuit layers.',
    price: 250,
    category: 'Desserts',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: '100% veg • Biscoff crust',
  },
  {
    id: 5,
    name: 'Blueberry Cheesecake Tub',
    subtitle: 'Cheesecake ai mirtilli freschi',
    description: 'Creamy, velvety veg cheesecake swirled with sweet blueberry compote.',
    price: 250,
    category: 'Desserts',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Blueberry compote',
  },
  {
    id: 6,
    name: 'Tiramisu Tub',
    subtitle: "Tiramisù classico all'italiana",
    description: 'Classic non-alcoholic tiramisu in a single-serve tub.',
    price: 230,
    category: 'Desserts',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Non-alcoholic • Classic',
  },
  {
    id: 7,
    name: 'Tres Leches Tub',
    subtitle: 'Torta tradizionale delle tre latti',
    description: 'Classic veg tres leches with soft sponge soaked in a rich three-milk blend.',
    price: 300,
    category: 'Desserts',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Three-milk sponge',
  },
  {
    id: 8,
    name: 'Tiramisu Tres Leches Tub',
    subtitle: 'Duo tiramisù e tre latti',
    description: 'Non-alcoholic tiramisu layered with tres leches sponge in one indulgent tub.',
    price: 400,
    category: 'Desserts',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Non-alcoholic • Fusion',
  },
  {
    id: 9,
    name: 'Gooey Cookie Tin',
    subtitle: 'Boîte de biscuits fondants',
    description: 'A tin of freshly baked, indulgently gooey cookies.',
    price: 250,
    category: 'Desserts',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Freshly baked • Gooey',
  },
  {
    id: 10,
    name: 'Chocolate Hazelnut Mousse Tub',
    subtitle: 'Mousse au chocolat et noisettes',
    description: 'Silky chocolate mousse with rich hazelnut notes.',
    price: 250,
    category: 'Desserts',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Silky • Hazelnut',
  },
  {
    id: 11,
    name: 'Nutella Buns',
    subtitle: 'Brioches dorées au Nutella',
    description: 'Soft, fluffy buns filled with rich, creamy Nutella. 100% veg.',
    price: 220,
    category: 'Desserts',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: '100% veg • Fluffy • Nutella',
  },

  // ── COLD COFFEE ──
  {
    id: 12,
    name: 'Desi Cold Coffee',
    subtitle: 'Caffè freddo classico',
    description: 'Classic Indian-style cold coffee, thick, chilled, and satisfying.',
    price: 155,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['classic'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Chilled',
  },
  {
    id: 13,
    name: 'Frappe Without Flavour',
    subtitle: 'Frappé au café pur',
    description: 'Blended espresso frappe with milk, smooth and refreshing.',
    price: 180,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Blended',
  },
  {
    id: 14,
    name: 'Frappe',
    subtitle: 'Frappé glacé aromatisé',
    description: 'Flavoured blended espresso frappe with milk.',
    price: 210,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Flavoured',
  },
  {
    id: 15,
    name: 'Mocha Frappe',
    subtitle: 'Frappé au moka et chocolat',
    description: 'Rich mocha blended with espresso and chilled milk.',
    price: 210,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Mocha',
  },
  {
    id: 16,
    name: 'Iced Latte Without Flavour',
    subtitle: 'Caffè latte freddo',
    description: 'Espresso poured over ice with chilled milk.',
    price: 180,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Espresso',
  },
  {
    id: 17,
    name: 'Iced Latte',
    subtitle: 'Caffè latte ghiacciato',
    description: 'Flavoured espresso over ice with chilled milk.',
    price: 210,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Flavoured',
  },
  {
    id: 18,
    name: 'Salted Caramel Iced Cappuccino',
    subtitle: 'Cappuccino al caramello salato',
    description: 'Iced cappuccino with a sweet and salty caramel twist.',
    price: 240,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Salted caramel',
  },
  {
    id: 19,
    name: 'Iced Cappuccino',
    subtitle: 'Cappuccino freddo con schiuma',
    description: 'Chilled cappuccino with airy milk foam over ice.',
    price: 240,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Milk based',
  },
  {
    id: 20,
    name: 'Vietnamese Iced Coffee',
    subtitle: 'Café glacé au lait concentré',
    description: 'Strong drip coffee with sweetened condensed milk over ice.',
    price: 240,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Condensed milk',
  },
  {
    id: 21,
    name: 'Spanish Iced Latte',
    subtitle: 'Café con leche helado',
    description: 'Espresso over ice with condensed milk for a smooth, sweet finish.',
    price: 240,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Condensed milk',
  },
  {
    id: 22,
    name: 'Iced Mocha',
    subtitle: 'Mocaccino freddo con cacao',
    description: 'Espresso with chocolate and chilled milk over ice.',
    price: 210,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Chocolate',
  },
  {
    id: 23,
    name: 'Iced Americano',
    subtitle: 'Caffè americano ghiacciato',
    description: 'Chilled espresso poured over ice. Bold, smooth, and refreshing.',
    price: 180,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['classic'],
    zone: 'cream',
    image: '',
    prep: 'Bold espresso • Ice',
  },
  {
    id: 24,
    name: 'Cranberry Espresso Tonic',
    subtitle: 'Espresso tonica ai mirtilli rossi',
    description: 'Cranberry, bold espresso, and crisp tonic with a balanced bitter-sweet flavour.',
    price: 210,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Espresso • Tonic • Cranberry',
  },
  {
    id: 25,
    name: 'Orange Espresso Tonic',
    subtitle: "Espresso tonica all'arancia",
    description: 'Zesty citrus, bold espresso, and refreshing fizzy tonic.',
    price: 210,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Espresso • Tonic • Orange',
  },
  {
    id: 26,
    name: 'Lavender Espresso Tonic',
    subtitle: 'Infusion lavande et tonique',
    description: 'Cold brew with aromatic lavender and zesty tonic.',
    price: 210,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Cold brew • Lavender • Tonic',
  },
  {
    id: 27,
    name: 'Classic Cold Brew',
    subtitle: 'Caffè estratto a freddo',
    description: 'Slow-brewed coffee with a smooth, refreshing and intensely aromatic flavour.',
    price: 220,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['signature'],
    zone: 'cream',
    image: '/images/signature-3.jpg',
    prep: 'Slow brewed • Smooth',
  },
  {
    id: 28,
    name: 'Orange Cold Brew',
    subtitle: 'Café infusé aux agrumes',
    description: 'Veg cold brew brightened with fresh orange notes.',
    price: 250,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Veg • Cold brew • Orange',
  },
  {
    id: 29,
    name: 'Cranberry Cold Brew',
    subtitle: 'Infusion froide aux canneberges',
    description: 'Smooth veg cold brew infused with tangy cranberry.',
    price: 250,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Veg • Cold brew • Cranberry',
  },
  {
    id: 30,
    name: 'Cold Brew',
    subtitle: 'Café infusé à froid artisanal',
    description: 'Slow-brewed coffee with a smooth, refreshing and intensely aromatic flavour.',
    price: 250,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Slow brewed 12+ hours',
  },
  {
    id: 31,
    name: 'Coconut Espresso Tonic',
    subtitle: 'Espresso tonica al cocco',
    description: 'Espresso blended with tropical coconut notes and fizzy tonic water.',
    price: 210,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Espresso • Coconut • Tonic',
  },

  // ── HOT COFFEE ──
  {
    id: 32,
    name: 'Cappuccino Without Flavour',
    subtitle: "Cappuccino all'italiana",
    description: 'Classic espresso with steamed and frothed milk.',
    price: 180,
    category: 'Hot Coffee',
    spiceLevel: 0,
    tags: ['classic'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Machine pulled',
  },
  {
    id: 33,
    name: 'Cappuccino',
    subtitle: 'Cappuccino aromatico',
    description: 'Flavoured cappuccino with espresso and silky steamed milk.',
    price: 210,
    category: 'Hot Coffee',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Flavoured',
  },
  {
    id: 34,
    name: 'Latte Without Flavour',
    subtitle: 'Caffellatte tradizionale',
    description: 'Espresso with a generous pour of steamed milk.',
    price: 180,
    category: 'Hot Coffee',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Machine pulled',
  },
  {
    id: 35,
    name: 'Latte',
    subtitle: 'Caffellatte aromatico',
    description: 'Flavoured espresso latte with velvety steamed milk.',
    price: 210,
    category: 'Hot Coffee',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Flavoured',
  },
  {
    id: 36,
    name: 'Flat White',
    subtitle: 'Doppio ristretto e micro-crema',
    description: 'Double ristretto with micro-foamed steamed milk — intense and smooth.',
    price: 180,
    category: 'Hot Coffee',
    spiceLevel: 0,
    tags: ['signature', 'bestseller'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Ristretto • Micro-foam',
  },
  {
    id: 37,
    name: 'Hot Mocha',
    subtitle: 'Mocaccino caldo al cacao',
    description: 'Espresso with rich chocolate and steamed milk.',
    price: 210,
    category: 'Hot Coffee',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Chocolate',
  },
  {
    id: 38,
    name: 'Espresso',
    subtitle: 'Caffè espresso perfetto',
    description: 'Rich, bold, intensely aromatic espresso.',
    price: 180,
    category: 'Hot Coffee',
    spiceLevel: 0,
    tags: ['classic'],
    zone: 'cream',
    image: '',
    prep: 'Double shot • Machine pulled',
  },
  {
    id: 39,
    name: 'Americano',
    subtitle: 'Caffè americano allungato',
    description: 'Bold espresso blended with hot water for a smooth, rich flavour.',
    price: 180,
    category: 'Hot Coffee',
    spiceLevel: 0,
    tags: ['classic'],
    zone: 'cream',
    image: '',
    prep: 'Espresso • Hot water',
  },

  // ── THICKSHAKES ──
  {
    id: 40,
    name: 'Passion Fruit & Orange Thickshake',
    subtitle: 'Frappé passion et orange',
    description: 'Creamy veg thickshake blending tangy passion fruit with refreshing orange.',
    price: 250,
    category: 'Shakes',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Passion fruit • Orange',
  },
  {
    id: 41,
    name: 'Cookie Crumble Thickshake',
    subtitle: 'Frappé aux éclats de biscuit',
    description: 'Creamy thickshake packed with crunchy cookie crumble.',
    price: 250,
    category: 'Shakes',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Cookie crumble topping',
  },
  {
    id: 42,
    name: 'Chocolate Brownie Thickshake',
    subtitle: 'Frappé au brownie fondant',
    description: 'Rich chocolate thickshake blended with fudgy brownie chunks.',
    price: 250,
    category: 'Shakes',
    spiceLevel: 0,
    tags: ['bestseller'],
    zone: 'cream',
    image: '',
    prep: 'Brownie blended in',
  },
  {
    id: 43,
    name: 'Decadent Chocolate Thickshake',
    subtitle: 'Frappé au chocolat noir intense',
    description: 'Rich, creamy veg thickshake loaded with intense chocolate flavour.',
    price: 250,
    category: 'Shakes',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Veg • Intense chocolate',
  },
  {
    id: 44,
    name: 'Mango Thickshake',
    subtitle: 'Frappé onctueux à la mangue',
    description: 'Creamy thickshake made with luscious Alphonso mangoes.',
    price: 250,
    category: 'Shakes',
    spiceLevel: 0,
    tags: ['seasonal'],
    zone: 'cream',
    image: '',
    prep: 'Alphonso mango',
  },

  // ── HOT DRINKS ──
  {
    id: 45,
    name: 'Hot Chocolate',
    subtitle: "Chocolat chaud à l'ancienne",
    description: 'Rich, creamy and velvety hot chocolate.',
    price: 210,
    category: 'Hot Drinks',
    spiceLevel: 0,
    tags: ['classic'],
    zone: 'cream',
    image: '',
    prep: 'Rich • Velvety',
  },
  {
    id: 46,
    name: 'Orange Hot Chocolate',
    subtitle: "Chocolat chaud à l'orange",
    description: 'Velvety hot chocolate infused with a citrusy orange twist.',
    price: 220,
    category: 'Hot Drinks',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Chocolate • Orange zest',
  },
  {
    id: 47,
    name: 'Ginger Lemon Honey Tea',
    subtitle: 'Infusion miel, citron et gingembre',
    description: 'Blend of zesty lemon, warm ginger, and sweet honey.',
    price: 220,
    category: 'Hot Drinks',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Ginger • Lemon • Honey',
  },
  {
    id: 48,
    name: 'Strawberry Hot Chocolate',
    subtitle: 'Chocolat chaud à la fraise',
    description: 'Creamy hot chocolate infused with real strawberry flavour.',
    price: 220,
    category: 'Hot Drinks',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Chocolate • Strawberry',
  },

  // ── COOLERS ──
  {
    id: 49,
    name: 'Kiwi Refresher',
    subtitle: 'Boisson fraîche au kiwi',
    description: 'Tangy, sweet drink bursting with real fruit texture.',
    price: 220,
    category: 'Coolers',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Real fruit • Tangy',
  },
  {
    id: 50,
    name: 'Apple Cinnamon Fizz',
    subtitle: 'Pétillant pomme et cannelle',
    description: 'Crisp apple with warm cinnamon in a fizzy blend.',
    price: 220,
    category: 'Coolers',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Apple • Cinnamon • Sparkling',
  },
  {
    id: 51,
    name: 'Cranberry Elderflower Chiller',
    subtitle: 'Pétillant canneberge et sureau',
    description: 'Cranberry and floral elderflower in a crisp, bubbly chiller.',
    price: 220,
    category: 'Coolers',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Cranberry • Elderflower',
  },
  {
    id: 52,
    name: 'Orange Vanilla Spritz',
    subtitle: "Spritz à l'orange et vanille",
    description: 'Zesty orange and smooth vanilla in a fizzy spritz.',
    price: 220,
    category: 'Coolers',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Orange • Vanilla • Fizzy',
  },
  {
    id: 53,
    name: 'Cold Chocolate',
    subtitle: 'Chocolat froid velouté',
    description: 'Rich, velvety, thick and creamy chilled chocolate drink.',
    price: 220,
    category: 'Coolers',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Rich • Chilled • Chocolate',
  },
  {
    id: 54,
    name: 'Tropical Iced Tea',
    subtitle: 'Thé glacé tropical aux agrumes',
    description: 'Fruity iced tea with a crisp, refreshing flavour.',
    price: 220,
    category: 'Coolers',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Fruity • Iced tea',
  },
  {
    id: 55,
    name: 'Spicy Guava Cooler',
    subtitle: 'Nectar de goyave épicé',
    description: 'Sweet guava juice with red chilli and chaat masala.',
    price: 220,
    category: 'Coolers',
    spiceLevel: 1,
    tags: ['special'],
    zone: 'red',
    image: '',
    prep: 'Guava • Chilli • Chaat masala',
  },

  // ── MATCHA ──
  {
    id: 56,
    name: 'Mango Matcha Serenity',
    subtitle: 'Matcha cérémonial à la mangue',
    description: 'Authentic matcha layered with sweet tropical mango.',
    price: 420,
    category: 'Matcha',
    spiceLevel: 0,
    tags: ['premium'],
    zone: 'cream',
    image: '',
    prep: 'Ceremonial matcha • Mango',
  },
  {
    id: 57,
    name: 'Berry Matcha Glow',
    subtitle: 'Matcha aux baies rouges',
    description: 'Premium earthy matcha blended with tangy berries.',
    price: 420,
    category: 'Matcha',
    spiceLevel: 0,
    tags: ['premium', 'popular'],
    zone: 'cream',
    image: '',
    prep: 'Premium matcha • Berries',
  },
  {
    id: 58,
    name: 'Coconut Cloud Matcha',
    subtitle: 'Matcha nuage de coco',
    description: 'Ceremonial matcha with coconut water, topped with creamy coconut foam.',
    price: 420,
    category: 'Matcha',
    spiceLevel: 0,
    tags: ['premium', 'special'],
    zone: 'cream',
    image: '',
    prep: 'Ceremonial matcha • Coconut foam',
  },

  // ── COOKIES ──
  {
    id: 59,
    name: 'Coconut Cookies',
    subtitle: 'Sablés à la noix de coco',
    description: 'Crispy, buttery cookies packed with toasted coconut flavour.',
    price: 220,
    category: 'Cookies',
    spiceLevel: 0,
    tags: ['classic'],
    zone: 'cream',
    image: '',
    prep: 'Buttery • Toasted coconut',
  },
  {
    id: 60,
    name: 'Cashew Sticks',
    subtitle: 'Bâtonnets aux noix de cajou',
    description: 'Crispy, golden-baked sticks packed with rich cashew flavour. 100% veg.',
    price: 300,
    category: 'Cookies',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: '100% veg • Cashew',
  },
  {
    id: 61,
    name: 'Double Chocolate Chip Cookies',
    subtitle: 'Biscuits double chocolat intense',
    description: 'Rich chocolate cookies loaded with premium chocolate chips.',
    price: 220,
    category: 'Cookies',
    spiceLevel: 0,
    tags: ['bestseller'],
    zone: 'cream',
    image: '',
    prep: 'Double chocolate • Premium chips',
  },
  {
    id: 62,
    name: 'Wheat & Dry Fruit Cookies',
    subtitle: 'Biscuits blé complet et fruits secs',
    description: 'Whole wheat cookies packed with crunchy dry fruits.',
    price: 275,
    category: 'Cookies',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Whole wheat • Dry fruits',
  },
  {
    id: 63,
    name: 'Orange & Cranberry Cookies',
    subtitle: 'Sablés orange et canneberges',
    description: 'Eggless cookies with zesty orange and tangy cranberries.',
    price: 275,
    category: 'Cookies',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Eggless • Orange • Cranberry',
  },
  {
    id: 64,
    name: 'Almond Sticks',
    subtitle: 'Bâtonnets feuilletés aux amandes',
    description: 'Golden-baked sticks topped with roasted almond slivers.',
    price: 300,
    category: 'Cookies',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Golden baked • Roasted almonds',
  },

  // ── NANKHATAI ──
  {
    id: 65,
    name: 'Rose Nankhatai',
    subtitle: 'Biscuits fondants à la rose',
    description: 'Melt-in-your-mouth veg nankhatai with an authentic, crumbly texture and aromatic rose flavour.',
    price: 300,
    category: 'Nankhatai',
    spiceLevel: 0,
    tags: ['traditional'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Rose • Crumbly',
  },
  {
    id: 66,
    name: 'Blueberry Nankhatai',
    subtitle: 'Sablés fondants aux myrtilles',
    description: 'Melt-in-your-mouth veg nankhatai cookies with sweet blueberry flavour and a traditional crumbly texture.',
    price: 300,
    category: 'Nankhatai',
    spiceLevel: 0,
    tags: ['traditional'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Blueberry • Crumbly',
  },

  // ── KHARI ──
  {
    id: 67,
    name: 'Amul Butter Khari',
    subtitle: 'Feuilletés croustillants pur beurre',
    description: 'Crispy, flaky puff layers baked with authentic Amul butter.',
    price: 165,
    category: 'Khari',
    spiceLevel: 0,
    tags: ['classic'],
    zone: 'cream',
    image: '',
    prep: 'Amul butter • Flaky puff',
  },
  {
    id: 68,
    name: 'Jeera Khari',
    subtitle: 'Feuilletés parfumés au cumin rôti',
    description: 'Crispy, flaky veg khari infused with aromatic roasted cumin.',
    price: 180,
    category: 'Khari',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Veg • Roasted cumin',
  },
  {
    id: 69,
    name: 'Methi Khari',
    subtitle: 'Feuilletés délicats au fenugrec',
    description: 'Crispy, flaky puff pastry infused with aromatic fenugreek.',
    price: 180,
    category: 'Khari',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Fenugreek • Flaky puff',
  },

  // ── RUSK ──
  {
    id: 70,
    name: 'Amul Butter Rusk',
    subtitle: 'Biscottes dorées au beurre',
    description: 'Crispy golden butter rusk with a rich, authentic tea-time flavour.',
    price: 180,
    category: 'Rusk',
    spiceLevel: 0,
    tags: ['classic'],
    zone: 'cream',
    image: '',
    prep: '100% veg • Amul butter',
  },

  // ── SANDWICHES ──
  {
    id: 71,
    name: 'Corn Spinach & Cheese Sandwich',
    subtitle: 'Croque épinards, maïs et fromage',
    description: 'Corn, fresh spinach, and melted cheese grilled to crispy perfection.',
    price: 210,
    category: 'Sandwiches',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Grilled • Corn • Spinach • Cheese',
  },
  {
    id: 72,
    name: 'Cheesy Garden Club Sandwich',
    subtitle: 'Club sandwich aux légumes du jardin',
    description: 'Layered club sandwich loaded with garden vegetables and melted cheese.',
    price: 210,
    category: 'Sandwiches',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Garden veg • Cheese',
  },
  {
    id: 73,
    name: 'Tandoori Paneer Sandwich',
    subtitle: 'Sandwich grillé au paneer tandoori',
    description: 'Smoky tandoori paneer with desi spices and crunchy vegetables in grilled bread.',
    price: 210,
    category: 'Sandwiches',
    spiceLevel: 1,
    tags: ['popular'],
    zone: 'red',
    image: '',
    prep: 'Tandoori paneer • Grilled',
  },

  // ── CAKES ──
  {
    id: 74,
    name: 'Nutella Brownie Cake',
    subtitle: 'Gâteau brownie au Nutella',
    description: 'Rich, fudgy veg brownie cake loaded with creamy Nutella.',
    price: 1000,
    category: 'Cakes',
    spiceLevel: 0,
    tags: ['bestseller'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Fudgy • Nutella',
  },
  {
    id: 75,
    name: 'Lotus Biscoff Baked Cheesecake',
    subtitle: 'Cheesecake cuit au spéculoos',
    description: 'Veg baked cheesecake with Lotus Biscoff spread and crunchy biscuit crust.',
    price: 1450,
    category: 'Cakes',
    spiceLevel: 0,
    tags: ['signature', 'bestseller'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Baked • Biscoff crust',
  },
  {
    id: 76,
    name: 'Chocolate Decadent Cake',
    subtitle: 'Gâteau moelleux tout chocolat',
    description: 'Ultra-rich, fudgy and meltingly soft chocolate cake.',
    price: 1000,
    category: 'Cakes',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Ultra-rich chocolate',
  },
  {
    id: 77,
    name: 'Lotus Biscoff Brownie Cake',
    subtitle: 'Gâteau brownie au caramel Biscoff',
    description: 'Fudgy chocolate brownie layers blended with caramelized Biscoff spread.',
    price: 1000,
    category: 'Cakes',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Brownie • Biscoff caramel',
  },
  {
    id: 78,
    name: 'Nutella Baked Cheesecake',
    subtitle: 'Gâteau au fromage cuit au Nutella',
    description: 'Rich veg baked cheesecake loaded with smooth Nutella.',
    price: 1450,
    category: 'Cakes',
    spiceLevel: 0,
    tags: ['signature', 'bestseller'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Baked • Nutella',
  },
  {
    id: 79,
    name: 'Blueberry Baked Cheesecake',
    subtitle: 'Cheesecake cuit aux myrtilles',
    description: 'Creamy blueberry cheesecake with a rich texture and berry tang.',
    price: 1450,
    category: 'Cakes',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Baked • Blueberry',
  },
  {
    id: 80,
    name: 'Chocolate Mousse Cake',
    subtitle: 'Entremets mousse au chocolat noir',
    description: 'Pure veg chocolate mousse cake with a creamy, velvety texture.',
    price: 1000,
    category: 'Cakes',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: '100% veg • Mousse • Velvety',
  },

  // ── ICE CREAMS ──
  {
    id: 81,
    name: 'Chocolate Chip Truffle',
    subtitle: 'Gelato al tartufo e cioccolato',
    description: 'Creamy veg ice cream with premium chocolate chip truffle.',
    price: 180,
    category: 'Ice Creams',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Veg • Chocolate chip',
  },
  {
    id: 82,
    name: 'Salted Caramel Avalanche',
    subtitle: 'Gelato al caramello salato',
    description: 'Creamy veg ice cream with smooth salted caramel ribbons.',
    price: 180,
    category: 'Ice Creams',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Salted caramel',
  },
  {
    id: 83,
    name: 'Walnut Espresso Indulgence',
    subtitle: "Gelato all'espresso e noci",
    description: 'Aromatic espresso with crunchy walnuts.',
    price: 180,
    category: 'Ice Creams',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Espresso • Walnut',
  },
  {
    id: 84,
    name: 'Roasted Almond Ice Cream',
    subtitle: 'Gelato alle mandorle tostate',
    description: 'Creamy veg ice cream loaded with slow-roasted almonds.',
    price: 180,
    category: 'Ice Creams',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Veg • Slow-roasted almonds',
  },
]

// Card tint by course
export const COURSE_TINT = {
  Desserts: 'bg-rose',
  'Cold Coffee': 'bg-turmeric',
  'Hot Coffee': 'bg-sand',
  Shakes: 'bg-turmeric',
  'Hot Drinks': 'bg-sand',
  Coolers: 'bg-sage',
  Matcha: 'bg-sage',
  Cookies: 'bg-sand',
  Nankhatai: 'bg-sand',
  Khari: 'bg-sand',
  Rusk: 'bg-sand',
  Sandwiches: 'bg-sage',
  Cakes: 'bg-rose',
  'Ice Creams': 'bg-turmeric',
}

// Default Courses
export const DEFAULT_COURSES = [
  { key: 'Desserts', title: 'Desserts', note: 'Cheesecake tubs, brownie tubs, buns & more' },
  { key: 'Cold Coffee', title: 'Cold Coffee', note: 'Frappes, iced lattes, cold brew & espresso tonics' },
  { key: 'Hot Coffee', title: 'Hot Coffee', note: 'Machine-pulled espresso, cappuccino & flat white' },
  { key: 'Shakes', title: 'Thickshakes', note: 'Thick, indulgent blended shakes' },
  { key: 'Hot Drinks', title: 'Hot Drinks', note: 'Hot chocolate, teas & specialty warm beverages' },
  { key: 'Coolers', title: 'Coolers', note: 'Refreshing fruit-based coolers & fizzy drinks' },
  { key: 'Matcha', title: 'Matcha', note: 'Ceremonial grade matcha in unique combinations' },
  { key: 'Cookies', title: 'Cookies', note: 'Fresh-baked cookies & sticks in 250 gm packs' },
  { key: 'Nankhatai', title: 'Nankhatai', note: 'Traditional melt-in-mouth nankhatai in 250 gm' },
  { key: 'Khari', title: 'Khari', note: 'Flaky buttered khari in 250 gm packs' },
  { key: 'Rusk', title: 'Rusk', note: 'Classic Amul butter rusk' },
  { key: 'Sandwiches', title: 'Sandwiches', note: 'Grilled sandwiches with fresh fillings' },
  { key: 'Cakes', title: 'Cakes', note: 'Whole cakes in 500 g — baked cheesecakes & brownie cakes' },
  { key: 'Ice Creams', title: 'Ice Creams', note: 'Premium artisan ice cream scoops' },
]

// Dishes carrying photography for the signature showcase
export const SIGNATURE_ITEMS = MENU_ITEMS.filter(item => item.image)

// Everything else
export const REST_OF_MENU = MENU_ITEMS.filter(item => !item.image)
