// Official Default Menu Items for The Bakerman Cafe
export const DEFAULT_MENU_ITEMS = [
  // ── DESSERTS ──
  {
    id: 1,
    name: 'Nutella Brownie Tub',
    subtitle: 'Gâteau fondant au Nutella',
    description: 'Rich, fudgy eggless Nutella brownie tub. Deeply chocolatey, gooey, and packed with authentic nutty goodness.',
    price: 200,
    category: 'Desserts',
    spiceLevel: 0,
    tags: ['signature', 'bestseller'],
    zone: 'cream',
    image: '/images/signature-1.jpg',
    prep: 'Eggless • Fudgy • Nutella',
    isHighlight: true,
    highlightOrder: 1, // Left flank in hero showcase
    isAvailable: true,
    sortOrder: 1,
  },
  {
    id: 2,
    name: 'Lotus Biscoff Brownie Tub',
    subtitle: 'Brownie au spéculoos Lotus',
    description: 'Fudgy veg brownie loaded with crunchy Lotus Biscoff spread and rich caramel flavour.',
    price: 200,
    category: 'Desserts',
    spiceLevel: 0,
    tags: ['bestseller'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Lotus Biscoff • Caramel',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 2,
  },
  {
    id: 3,
    name: 'Nutella Cheesecake Tub',
    subtitle: 'Torta al formaggio e Nutella',
    description: 'Creamy eggless cheesecake layered with rich, velvety Nutella.',
    price: 250,
    category: 'Desserts',
    spiceLevel: 0,
    tags: ['signature', 'bestseller'],
    zone: 'cream',
    image: '/images/signature-2.jpg',
    prep: 'Eggless • Baked • Nutella',
    isHighlight: true,
    highlightOrder: 2, // Center hero plate
    isAvailable: true,
    sortOrder: 3,
  },
  {
    id: 4,
    name: 'Lotus Biscoff Cheesecake Tub',
    subtitle: 'Cheesecake al caramello Biscoff',
    description: '100% veg cheesecake with silky cream cheese and crunchy caramelized Biscoff biscuit layers.',
    price: 250,
    category: 'Desserts',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: '100% veg • Biscoff crust',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 4,
  },
  {
    id: 5,
    name: 'Blueberry Cheesecake Tub',
    subtitle: 'Cheesecake ai mirtilli freschi',
    description: 'Creamy, velvety veg cheesecake swirled with sweet blueberry compote.',
    price: 250,
    category: 'Desserts',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Blueberry compote',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 5,
  },
  {
    id: 6,
    name: 'Tiramisu Tub',
    subtitle: "Tiramisù classico all'italiana",
    description: 'Classic non-alcoholic tiramisu in a single-serve tub.',
    price: 230,
    category: 'Desserts',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Non-alcoholic • Classic',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 6,
  },
  {
    id: 7,
    name: 'Tres Leches Tub',
    subtitle: 'Torta tradizionale delle tre latti',
    description: 'Classic veg tres leches with soft sponge soaked in a rich three-milk blend.',
    price: 300,
    category: 'Desserts',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Three-milk sponge',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 7,
  },
  {
    id: 8,
    name: 'Tiramisu Tres Leches Tub',
    subtitle: 'Duo tiramisù e tre latti',
    description: 'Non-alcoholic tiramisu layered with tres leches sponge in one indulgent tub.',
    price: 400,
    category: 'Desserts',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Non-alcoholic • Fusion',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 8,
  },
  {
    id: 9,
    name: 'Gooey Cookie Tin',
    subtitle: 'Boîte de biscuits fondants',
    description: 'A tin of freshly baked, indulgently gooey cookies.',
    price: 250,
    category: 'Desserts',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Freshly baked • Gooey',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 9,
  },
  {
    id: 10,
    name: 'Chocolate Hazelnut Mousse Tub',
    subtitle: 'Mousse au chocolat et noisettes',
    description: 'Silky chocolate mousse with rich hazelnut notes.',
    price: 250,
    category: 'Desserts',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Silky • Hazelnut',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 10,
  },
  {
    id: 11,
    name: 'Nutella Buns',
    subtitle: 'Brioches dorées au Nutella',
    description: 'Soft, fluffy buns filled with rich, creamy Nutella. 100% veg.',
    price: 220,
    category: 'Desserts',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: '100% veg • Fluffy • Nutella',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 11,
  },

  // ── COLD COFFEE ──
  {
    id: 12,
    name: 'Desi Cold Coffee',
    subtitle: 'Caffè freddo classico',
    description: 'Classic Indian-style cold coffee, thick, chilled, and satisfying.',
    price: 155,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['classic'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Chilled',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 12,
  },
  {
    id: 13,
    name: 'Frappe Without Flavour',
    subtitle: 'Frappé au café pur',
    description: 'Blended espresso frappe with milk, smooth and refreshing.',
    price: 180,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Blended',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 13,
  },
  {
    id: 14,
    name: 'Frappe',
    subtitle: 'Frappé glacé aromatisé',
    description: 'Flavoured blended espresso frappe with milk.',
    price: 210,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Flavoured',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 14,
  },
  {
    id: 15,
    name: 'Mocha Frappe',
    subtitle: 'Frappé au moka et chocolat',
    description: 'Rich mocha blended with espresso and chilled milk.',
    price: 210,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Mocha',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 15,
  },
  {
    id: 16,
    name: 'Iced Latte Without Flavour',
    subtitle: 'Caffè latte freddo',
    description: 'Espresso poured over ice with chilled milk.',
    price: 180,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Espresso',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 16,
  },
  {
    id: 17,
    name: 'Iced Latte',
    subtitle: 'Caffè latte ghiacciato',
    description: 'Flavoured espresso over ice with chilled milk.',
    price: 210,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Flavoured',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 17,
  },
  {
    id: 18,
    name: 'Salted Caramel Iced Cappuccino',
    subtitle: 'Cappuccino al caramello salato',
    description: 'Iced cappuccino with a sweet and salty caramel twist.',
    price: 240,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Salted caramel',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 18,
  },
  {
    id: 19,
    name: 'Iced Cappuccino',
    subtitle: 'Cappuccino freddo con schiuma',
    description: 'Chilled cappuccino with airy milk foam over ice.',
    price: 240,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Milk based',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 19,
  },
  {
    id: 20,
    name: 'Vietnamese Iced Coffee',
    subtitle: 'Café glacé au lait concentré',
    description: 'Strong drip coffee with sweetened condensed milk over ice.',
    price: 240,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Condensed milk',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 20,
  },
  {
    id: 21,
    name: 'Spanish Iced Latte',
    subtitle: 'Café con leche helado',
    description: 'Espresso over ice with condensed milk for a smooth, sweet finish.',
    price: 240,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Condensed milk',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 21,
  },
  {
    id: 22,
    name: 'Iced Mocha',
    subtitle: 'Mocaccino freddo con cacao',
    description: 'Espresso with chocolate and chilled milk over ice.',
    price: 210,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Chocolate',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 22,
  },
  {
    id: 23,
    name: 'Iced Americano',
    subtitle: 'Caffè americano ghiacciato',
    description: 'Chilled espresso poured over ice. Bold, smooth, and refreshing.',
    price: 180,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['classic'],
    zone: 'cream',
    image: '',
    prep: 'Bold espresso • Ice',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 23,
  },
  {
    id: 24,
    name: 'Cranberry Espresso Tonic',
    subtitle: 'Espresso tonica ai mirtilli rossi',
    description: 'Cranberry, bold espresso, and crisp tonic with a balanced bitter-sweet flavour.',
    price: 210,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Espresso • Tonic • Cranberry',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 24,
  },
  {
    id: 25,
    name: 'Orange Espresso Tonic',
    subtitle: "Espresso tonica all'arancia",
    description: 'Zesty citrus, bold espresso, and refreshing fizzy tonic.',
    price: 210,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Espresso • Tonic • Orange',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 25,
  },
  {
    id: 26,
    name: 'Lavender Espresso Tonic',
    subtitle: 'Infusion lavande et tonique',
    description: 'Cold brew with aromatic lavender and zesty tonic.',
    price: 210,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Cold brew • Lavender • Tonic',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 26,
  },
  {
    id: 27,
    name: 'Classic Cold Brew',
    subtitle: 'Caffè estratto a freddo',
    description: 'Slow-brewed coffee with a smooth, refreshing and intensely aromatic flavour.',
    price: 220,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['signature'],
    zone: 'cream',
    image: '/images/signature-3.jpg',
    prep: 'Slow brewed • Smooth',
    isHighlight: true,
    highlightOrder: 3, // Right flank in hero showcase
    isAvailable: true,
    sortOrder: 27,
  },
  {
    id: 28,
    name: 'Orange Cold Brew',
    subtitle: 'Café infusé aux agrumes',
    description: 'Veg cold brew brightened with fresh orange notes.',
    price: 250,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Veg • Cold brew • Orange',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 28,
  },
  {
    id: 29,
    name: 'Cranberry Cold Brew',
    subtitle: 'Infusion froide aux canneberges',
    description: 'Smooth veg cold brew infused with tangy cranberry.',
    price: 250,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Veg • Cold brew • Cranberry',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 29,
  },
  {
    id: 30,
    name: 'Cold Brew',
    subtitle: 'Café infusé à froid artisanal',
    description: 'Slow-brewed coffee with a smooth, refreshing and intensely aromatic flavour.',
    price: 250,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Slow brewed 12+ hours',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 30,
  },
  {
    id: 31,
    name: 'Coconut Espresso Tonic',
    subtitle: 'Espresso tonica al cocco',
    description: 'Espresso blended with tropical coconut notes and fizzy tonic water.',
    price: 210,
    category: 'Cold Coffee',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Espresso • Coconut • Tonic',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 31,
  },

  // ── HOT COFFEE ──
  {
    id: 32,
    name: 'Cappuccino Without Flavour',
    subtitle: "Cappuccino all'italiana",
    description: 'Classic espresso with steamed and frothed milk.',
    price: 180,
    category: 'Hot Coffee',
    spiceLevel: 0,
    tags: ['classic'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Machine pulled',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 32,
  },
  {
    id: 33,
    name: 'Cappuccino',
    subtitle: 'Cappuccino aromatico',
    description: 'Flavoured cappuccino with espresso and silky steamed milk.',
    price: 210,
    category: 'Hot Coffee',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Flavoured',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 33,
  },
  {
    id: 34,
    name: 'Latte Without Flavour',
    subtitle: 'Caffellatte tradizionale',
    description: 'Espresso with a generous pour of steamed milk.',
    price: 180,
    category: 'Hot Coffee',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Machine pulled',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 34,
  },
  {
    id: 35,
    name: 'Latte',
    subtitle: 'Caffellatte aromatico',
    description: 'Flavoured espresso latte with velvety steamed milk.',
    price: 210,
    category: 'Hot Coffee',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Flavoured',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 35,
  },
  {
    id: 36,
    name: 'Flat White',
    subtitle: 'Doppio ristretto e micro-crema',
    description: 'Double ristretto with micro-foamed steamed milk — intense and smooth.',
    price: 180,
    category: 'Hot Coffee',
    spiceLevel: 0,
    tags: ['signature', 'bestseller'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Ristretto • Micro-foam',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 36,
  },
  {
    id: 37,
    name: 'Hot Mocha',
    subtitle: 'Mocaccino caldo al cacao',
    description: 'Espresso with rich chocolate and steamed milk.',
    price: 210,
    category: 'Hot Coffee',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Milk based • Chocolate',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 37,
  },
  {
    id: 38,
    name: 'Espresso',
    subtitle: 'Caffè espresso perfetto',
    description: 'Rich, bold, intensely aromatic espresso.',
    price: 180,
    category: 'Hot Coffee',
    spiceLevel: 0,
    tags: ['classic'],
    zone: 'cream',
    image: '',
    prep: 'Double shot • Machine pulled',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 38,
  },
  {
    id: 39,
    name: 'Americano',
    subtitle: 'Caffè americano allungato',
    description: 'Bold espresso blended with hot water for a smooth, rich flavour.',
    price: 180,
    category: 'Hot Coffee',
    spiceLevel: 0,
    tags: ['classic'],
    zone: 'cream',
    image: '',
    prep: 'Espresso • Hot water',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 39,
  },

  // ── THICKSHAKES ──
  {
    id: 40,
    name: 'Passion Fruit & Orange Thickshake',
    subtitle: 'Frappé passion et orange',
    description: 'Creamy veg thickshake blending tangy passion fruit with refreshing orange.',
    price: 250,
    category: 'Shakes',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Passion fruit • Orange',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 40,
  },
  {
    id: 41,
    name: 'Cookie Crumble Thickshake',
    subtitle: 'Frappé aux éclats de biscuit',
    description: 'Creamy thickshake packed with crunchy cookie crumble.',
    price: 250,
    category: 'Shakes',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Cookie crumble topping',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 41,
  },
  {
    id: 42,
    name: 'Chocolate Brownie Thickshake',
    subtitle: 'Frappé au brownie fondant',
    description: 'Rich chocolate thickshake blended with fudgy brownie chunks.',
    price: 250,
    category: 'Shakes',
    spiceLevel: 0,
    tags: ['bestseller'],
    zone: 'cream',
    image: '',
    prep: 'Brownie blended in',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 42,
  },
  {
    id: 43,
    name: 'Decadent Chocolate Thickshake',
    subtitle: 'Frappé au chocolat noir intense',
    description: 'Rich, creamy veg thickshake loaded with intense chocolate flavour.',
    price: 250,
    category: 'Shakes',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Veg • Intense chocolate',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 43,
  },
  {
    id: 44,
    name: 'Mango Thickshake',
    subtitle: 'Frappé onctueux à la mangue',
    description: 'Creamy thickshake made with luscious Alphonso mangoes.',
    price: 250,
    category: 'Shakes',
    spiceLevel: 0,
    tags: ['seasonal'],
    zone: 'cream',
    image: '',
    prep: 'Alphonso mango',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 44,
  },

  // ── HOT DRINKS ──
  {
    id: 45,
    name: 'Hot Chocolate',
    subtitle: "Chocolat chaud à l'ancienne",
    description: 'Rich, creamy and velvety hot chocolate.',
    price: 210,
    category: 'Hot Drinks',
    spiceLevel: 0,
    tags: ['classic'],
    zone: 'cream',
    image: '',
    prep: 'Rich • Velvety',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 45,
  },
  {
    id: 46,
    name: 'Orange Hot Chocolate',
    subtitle: "Chocolat chaud à l'orange",
    description: 'Velvety hot chocolate infused with a citrusy orange twist.',
    price: 220,
    category: 'Hot Drinks',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Chocolate • Orange zest',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 46,
  },
  {
    id: 47,
    name: 'Ginger Lemon Honey Tea',
    subtitle: 'Infusion miel, citron et gingembre',
    description: 'Blend of zesty lemon, warm ginger, and sweet honey.',
    price: 220,
    category: 'Hot Drinks',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Ginger • Lemon • Honey',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 47,
  },
  {
    id: 48,
    name: 'Strawberry Hot Chocolate',
    subtitle: 'Chocolat chaud à la fraise',
    description: 'Creamy hot chocolate infused with real strawberry flavour.',
    price: 220,
    category: 'Hot Drinks',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Chocolate • Strawberry',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 48,
  },

  // ── COOLERS ──
  {
    id: 49,
    name: 'Kiwi Refresher',
    subtitle: 'Boisson fraîche au kiwi',
    description: 'Tangy, sweet drink bursting with real fruit texture.',
    price: 220,
    category: 'Coolers',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Real fruit • Tangy',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 49,
  },
  {
    id: 50,
    name: 'Apple Cinnamon Fizz',
    subtitle: 'Pétillant pomme et cannelle',
    description: 'Crisp apple with warm cinnamon in a fizzy blend.',
    price: 220,
    category: 'Coolers',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Apple • Cinnamon • Sparkling',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 50,
  },
  {
    id: 51,
    name: 'Cranberry Elderflower Chiller',
    subtitle: 'Pétillant canneberge et sureau',
    description: 'Cranberry and floral elderflower in a crisp, bubbly chiller.',
    price: 220,
    category: 'Coolers',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Cranberry • Elderflower',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 51,
  },
  {
    id: 52,
    name: 'Orange Vanilla Spritz',
    subtitle: "Spritz à l'orange et vanille",
    description: 'Zesty orange and smooth vanilla in a fizzy spritz.',
    price: 220,
    category: 'Coolers',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Orange • Vanilla • Fizzy',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 52,
  },
  {
    id: 53,
    name: 'Cold Chocolate',
    subtitle: 'Chocolat froid velouté',
    description: 'Rich, velvety, thick and creamy chilled chocolate drink.',
    price: 220,
    category: 'Coolers',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Rich • Chilled • Chocolate',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 53,
  },
  {
    id: 54,
    name: 'Tropical Iced Tea',
    subtitle: 'Thé glacé tropical aux agrumes',
    description: 'Fruity iced tea with a crisp, refreshing flavour.',
    price: 220,
    category: 'Coolers',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Fruity • Iced tea',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 54,
  },
  {
    id: 55,
    name: 'Spicy Guava Cooler',
    subtitle: 'Nectar de goyave épicé',
    description: 'Sweet guava juice with red chilli and chaat masala.',
    price: 220,
    category: 'Coolers',
    spiceLevel: 1,
    tags: ['special'],
    zone: 'red',
    image: '',
    prep: 'Guava • Chilli • Chaat masala',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 55,
  },

  // ── MATCHA ──
  {
    id: 56,
    name: 'Mango Matcha Serenity',
    subtitle: 'Matcha cérémonial à la mangue',
    description: 'Authentic matcha layered with sweet tropical mango.',
    price: 420,
    category: 'Matcha',
    spiceLevel: 0,
    tags: ['premium'],
    zone: 'cream',
    image: '',
    prep: 'Ceremonial matcha • Mango',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 56,
  },
  {
    id: 57,
    name: 'Berry Matcha Glow',
    subtitle: 'Matcha aux baies rouges',
    description: 'Premium earthy matcha blended with tangy berries.',
    price: 420,
    category: 'Matcha',
    spiceLevel: 0,
    tags: ['premium', 'popular'],
    zone: 'cream',
    image: '',
    prep: 'Premium matcha • Berries',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 57,
  },
  {
    id: 58,
    name: 'Coconut Cloud Matcha',
    subtitle: 'Matcha nuage de coco',
    description: 'Ceremonial matcha with coconut water, topped with creamy coconut foam.',
    price: 420,
    category: 'Matcha',
    spiceLevel: 0,
    tags: ['premium', 'special'],
    zone: 'cream',
    image: '',
    prep: 'Ceremonial matcha • Coconut foam',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 58,
  },

  // ── COOKIES ──
  {
    id: 59,
    name: 'Coconut Cookies',
    subtitle: 'Sablés à la noix de coco',
    description: 'Crispy, buttery cookies packed with toasted coconut flavour.',
    price: 220,
    category: 'Cookies',
    spiceLevel: 0,
    tags: ['classic'],
    zone: 'cream',
    image: '',
    prep: 'Buttery • Toasted coconut',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 59,
  },
  {
    id: 60,
    name: 'Cashew Sticks',
    subtitle: 'Bâtonnets aux noix de cajou',
    description: 'Crispy, golden-baked sticks packed with rich cashew flavour. 100% veg.',
    price: 300,
    category: 'Cookies',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: '100% veg • Cashew',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 60,
  },
  {
    id: 61,
    name: 'Double Chocolate Chip Cookies',
    subtitle: 'Biscuits double chocolat intense',
    description: 'Rich chocolate cookies loaded with premium chocolate chips.',
    price: 220,
    category: 'Cookies',
    spiceLevel: 0,
    tags: ['bestseller'],
    zone: 'cream',
    image: '',
    prep: 'Double chocolate • Premium chips',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 61,
  },
  {
    id: 62,
    name: 'Wheat & Dry Fruit Cookies',
    subtitle: 'Biscuits blé complet et fruits secs',
    description: 'Whole wheat cookies packed with crunchy dry fruits.',
    price: 275,
    category: 'Cookies',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Whole wheat • Dry fruits',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 62,
  },
  {
    id: 63,
    name: 'Orange & Cranberry Cookies',
    subtitle: 'Sablés orange et canneberges',
    description: 'Eggless cookies with zesty orange and tangy cranberries.',
    price: 275,
    category: 'Cookies',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Eggless • Orange • Cranberry',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 63,
  },
  {
    id: 64,
    name: 'Almond Sticks',
    subtitle: 'Bâtonnets feuilletés aux amandes',
    description: 'Golden-baked sticks topped with roasted almond slivers.',
    price: 300,
    category: 'Cookies',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Golden baked • Roasted almonds',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 64,
  },

  // ── NANKHATAI ──
  {
    id: 65,
    name: 'Rose Nankhatai',
    subtitle: 'Biscuits fondants à la rose',
    description: 'Melt-in-your-mouth veg nankhatai with an authentic, crumbly texture and aromatic rose flavour.',
    price: 300,
    category: 'Nankhatai',
    spiceLevel: 0,
    tags: ['traditional'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Rose • Crumbly',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 65,
  },
  {
    id: 66,
    name: 'Blueberry Nankhatai',
    subtitle: 'Sablés fondants aux myrtilles',
    description: 'Melt-in-your-mouth veg nankhatai cookies with sweet blueberry flavour and a traditional crumbly texture.',
    price: 300,
    category: 'Nankhatai',
    spiceLevel: 0,
    tags: ['traditional'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Blueberry • Crumbly',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 66,
  },

  // ── KHARI ──
  {
    id: 67,
    name: 'Amul Butter Khari',
    subtitle: 'Feuilletés croustillants pur beurre',
    description: 'Crispy, flaky puff layers baked with authentic Amul butter.',
    price: 165,
    category: 'Khari',
    spiceLevel: 0,
    tags: ['classic'],
    zone: 'cream',
    image: '',
    prep: 'Amul butter • Flaky puff',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 67,
  },
  {
    id: 68,
    name: 'Jeera Khari',
    subtitle: 'Feuilletés parfumés au cumin rôti',
    description: 'Crispy, flaky veg khari infused with aromatic roasted cumin.',
    price: 180,
    category: 'Khari',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Veg • Roasted cumin',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 68,
  },
  {
    id: 69,
    name: 'Methi Khari',
    subtitle: 'Feuilletés délicats au fenugrec',
    description: 'Crispy, flaky puff pastry infused with aromatic fenugreek.',
    price: 180,
    category: 'Khari',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Fenugreek • Flaky puff',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 69,
  },

  // ── RUSK ──
  {
    id: 70,
    name: 'Amul Butter Rusk',
    subtitle: 'Biscottes dorées au beurre',
    description: 'Crispy golden butter rusk with a rich, authentic tea-time flavour.',
    price: 180,
    category: 'Rusk',
    spiceLevel: 0,
    tags: ['classic'],
    zone: 'cream',
    image: '',
    prep: '100% veg • Amul butter',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 70,
  },

  // ── SANDWICHES ──
  {
    id: 71,
    name: 'Corn Spinach & Cheese Sandwich',
    subtitle: 'Croque épinards, maïs et fromage',
    description: 'Corn, fresh spinach, and melted cheese grilled to crispy perfection.',
    price: 210,
    category: 'Sandwiches',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Grilled • Corn • Spinach • Cheese',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 71,
  },
  {
    id: 72,
    name: 'Cheesy Garden Club Sandwich',
    subtitle: 'Club sandwich aux légumes du jardin',
    description: 'Layered club sandwich loaded with garden vegetables and melted cheese.',
    price: 210,
    category: 'Sandwiches',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Garden veg • Cheese',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 72,
  },
  {
    id: 73,
    name: 'Tandoori Paneer Sandwich',
    subtitle: 'Sandwich grillé au paneer tandoori',
    description: 'Smoky tandoori paneer with desi spices and crunchy vegetables in grilled bread.',
    price: 210,
    category: 'Sandwiches',
    spiceLevel: 1,
    tags: ['popular'],
    zone: 'red',
    image: '',
    prep: 'Tandoori paneer • Grilled',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 73,
  },

  // ── CAKES ──
  {
    id: 74,
    name: 'Nutella Brownie Cake',
    subtitle: 'Gâteau brownie au Nutella',
    description: 'Rich, fudgy veg brownie cake loaded with creamy Nutella.',
    price: 1000,
    category: 'Cakes',
    spiceLevel: 0,
    tags: ['bestseller'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Fudgy • Nutella',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 74,
  },
  {
    id: 75,
    name: 'Lotus Biscoff Baked Cheesecake',
    subtitle: 'Cheesecake cuit au spéculoos',
    description: 'Veg baked cheesecake with Lotus Biscoff spread and crunchy biscuit crust.',
    price: 1450,
    category: 'Cakes',
    spiceLevel: 0,
    tags: ['signature', 'bestseller'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Baked • Biscoff crust',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 75,
  },
  {
    id: 76,
    name: 'Chocolate Decadent Cake',
    subtitle: 'Gâteau moelleux tout chocolat',
    description: 'Ultra-rich, fudgy and meltingly soft chocolate cake.',
    price: 1000,
    category: 'Cakes',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Ultra-rich chocolate',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 76,
  },
  {
    id: 77,
    name: 'Lotus Biscoff Brownie Cake',
    subtitle: 'Gâteau brownie au caramel Biscoff',
    description: 'Fudgy chocolate brownie layers blended with caramelized Biscoff spread.',
    price: 1000,
    category: 'Cakes',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Brownie • Biscoff caramel',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 77,
  },
  {
    id: 78,
    name: 'Nutella Baked Cheesecake',
    subtitle: 'Gâteau au fromage cuit au Nutella',
    description: 'Rich veg baked cheesecake loaded with smooth Nutella.',
    price: 1450,
    category: 'Cakes',
    spiceLevel: 0,
    tags: ['signature', 'bestseller'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Baked • Nutella',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 78,
  },
  {
    id: 79,
    name: 'Blueberry Baked Cheesecake',
    subtitle: 'Cheesecake cuit aux myrtilles',
    description: 'Creamy blueberry cheesecake with a rich texture and berry tang.',
    price: 1450,
    category: 'Cakes',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Baked • Blueberry',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 79,
  },
  {
    id: 80,
    name: 'Chocolate Mousse Cake',
    subtitle: 'Entremets mousse au chocolat noir',
    description: 'Pure veg chocolate mousse cake with a creamy, velvety texture.',
    price: 1000,
    category: 'Cakes',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: '100% veg • Mousse • Velvety',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 80,
  },

  // ── ICE CREAMS ──
  {
    id: 81,
    name: 'Chocolate Chip Truffle',
    subtitle: 'Gelato al tartufo e cioccolato',
    description: 'Creamy veg ice cream with premium chocolate chip truffle.',
    price: 180,
    category: 'Ice Creams',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Veg • Chocolate chip',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 81,
  },
  {
    id: 82,
    name: 'Salted Caramel Avalanche',
    subtitle: 'Gelato al caramello salato',
    description: 'Creamy veg ice cream with smooth salted caramel ribbons.',
    price: 180,
    category: 'Ice Creams',
    spiceLevel: 0,
    tags: ['popular'],
    zone: 'cream',
    image: '',
    prep: 'Veg • Salted caramel',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 82,
  },
  {
    id: 83,
    name: 'Walnut Espresso Indulgence',
    subtitle: "Gelato all'espresso e noci",
    description: 'Aromatic espresso with crunchy walnuts.',
    price: 180,
    category: 'Ice Creams',
    spiceLevel: 0,
    tags: ['special'],
    zone: 'cream',
    image: '',
    prep: 'Espresso • Walnut',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 83,
  },
  {
    id: 84,
    name: 'Roasted Almond Ice Cream',
    subtitle: 'Gelato alle mandorle tostate',
    description: 'Creamy veg ice cream loaded with slow-roasted almonds.',
    price: 180,
    category: 'Ice Creams',
    spiceLevel: 0,
    tags: [],
    zone: 'cream',
    image: '',
    prep: 'Veg • Slow-roasted almonds',
    isHighlight: false,
    highlightOrder: 0,
    isAvailable: true,
    sortOrder: 84,
  },
]
